export const LOAD_CARS_SUCCESS = "LOAD_CARS_SUCCESS";
export const CREATE_CAR_SUCCESS = "CREAE_CAR_SUCCESS";
export const UPDATE_CAR_SUCCESS = "UPDATE_CAR_SUCCESS";
export const LOAD_SELLERS_SUCCESS = "LOAD_SELLERS_SUCCESS";
export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const DELETE_CAR_OPTIMISTIC = "DELETE_CAR_OPTIMISTIC";